### ISSUE TITLE
Imposible to add new track on Windows 7

### ISSUE THREAD

**Issue by devops85** [jhurliman/node-echoprint-server#2]
Hi,
Your project is amazing. I am trying to install it on Windows. Everything looks fine, but I am faccing an issue when I try to add a new record.
This message appears: 

debug: No matched tracks
debug: Track does not exist in the database yet, status NO_RESULTS
info: Creating track TR3CLO6IH55Y48CW ("Tainted")
error: Failed to ingest track: Error: ENOENT, open 'C:\tmp\echoprint-TR3CLO6IH55
Y48CW'

Could you please shed some light here?

Thank you very much.

**Comment by jhurliman** [comment]
Ah, there is a lazy assumption in there assuming /tmp/ exists. I can fix that to use the correct temp dir for the platform. As a quick hack try creating C:\tmp\

**Comment by devops85** [comment]
Thanks man,
This hack works!! :) Do you know which line in the code we have to change in order to set a new temp dir?.
Thanks

**Comment by jhurliman** [comment]
I just committed 6ea272bf7c05740939e2e9e338e3a4fa917b896f which should address this issue. It uses a platform-agnostic library called node-temp to find the temporary directory on your machine instead of hardcoding /tmp/. Let me know if you have any issues with this and I'll reopen the ticket. Thanks for the report!
